/**************************************************************************************************\
* enigmaGeocaching.c
* 
* Problems from Geocaching. theThirdProblem, theFourthProblem, theFifthProblem
* 
\**************************************************************************************************/
#include <stdio.h>
#include <stdbool.h>
#include <malloc.h>
#include <string.h>

#include "enigma.h"
#include "log.h"
#include "toolbox.h"
#include "coincidence.h"
#include "ngramScore.h"
#include "generics/workDispatcher.h"

char text11_test[]  = "QAVIMKGJZTXYFBCMVCONNTBZKLEZNBQMCLEUQXPYTYHEBVNCKOVACPK"
                      "GCWPWUVHUFWJFWTCNIJVULFBVADZRQWMLVDDQFRJAZUPSIXACSKJHLR"
                      "DQFMXPSZMKI";


EnigmaSettings  fourthProblemTest=
{
    3,
    {
        "III",
        "I",
        "II"
    },
    "UKW B",
    {
        1, 1, 1
    },
    {
        1, 17, 12
    },
    "AZ BY CX DW EV FU GT HS IQ JR",
    "QAVIM KGJZT XYFBC MVCON NTBZK LEZNB QMCLE UQXPY TYHEB VNCKO VACPK "
    "GCWPW UVHUF WJFWT CNIJV ULFBV ADZRQ WMLVD DQFRJ AZUPS IXACS KJHLR "
    "DQFMX PSZMK I"
};

/**************************************************************************************************\
* 
* Geocache GCXQHW, Athens enigma
* https://www.geocaching.com/geocache/GCXQHW
* SOLVED
*
\**************************************************************************************************/
// https://www.geocaching.com/geocache/GCXQHW Athents Engima
// Walze settings as indicated, R1=1, R2=2, R3=3, no steckers
EnigmaSettings  GCXQHWTest=
{
    3,
    {
        "IV",
        "III",
        "V"
    },
    "UKW B",
    {
        1, 1, 1
    },
    {
        1, 1, 1 // unknown
    },
    "",
    "IFKIN OXPBU ELULE UEHNF KVJCW"
    "XCTWM AFEFZ VGUVA CTASQ CYIAM"
    "GEBFH DXRWK UOFNY JJWPI FUESJ"
    "JGYUR IRAQI XQAPP QQ"
};

void gcAthentsEnigma()
{
    printf("#####################################################################################\n");
    printf("# GEOCACHE GCXQHW, Athens enigma\n");
    printf("#####################################################################################\n");

    // FROM THE GEOCACHE WE KNOW FOLLOWING:
    // IV III V, UKW B, no steckers R1=1, R2=1, R3=1
    // We create a custom permutations list with just one permutation
    LinkedList*     permutations=linkedListCreate();
    int*            permutation =malloc(4*sizeof(int));
    permutation[0]=1; // Index of UKW B
    permutation[1]=3; // IV
    permutation[2]=2; // III
    permutation[3]=4; // V
    linkedListAppendObject(permutations, permutation);

    // program the IoC solver
    IocRecipe recipe;
    recipe.enigmaType       =ENIGMATYPE_M3;
    recipe.walzeSet         =M3_ARMY_1938;
    recipe.method           =DEPTH_NONE;
    recipe.evalWalzen       =EVAL_IOC;
    recipe.evalSteckers     =EVAL_IOC;
    recipe.maxSteckers      =0;
    recipe.maxSteckersInline=0;
    recipe.ngramSize        =0;
    strncpy(recipe.ngramSet, "GC", MAX_NGRAMSETSIZE);
    recipe.scoreListSize    =25;
    recipe.numberOfSolutions=3;
    recipe.numberOfThreads  =1;
    recipe.cipher           =GCXQHWTest.cipher;
    recipe.cipherSize       =MAX_TEXT;
    iocDecodeText(recipe, permutations);
    destroyPermutations(permutations);
}

/**************************************************************************************************\
* Enigma cipher from GC6ZZBB geochache. It is a short cipher.
* FROM THE GEOCACHE WE KNOW FOLLOWING:
* - http://enigmaco.de/enigma/enigma_de.html was used to encrypt; therefore
* - Three Walzen out of I-V
* - R1 = R2 = R3 = 1
* - UKW B
* - up to 13 steckers
* - Language is probably german
* NOT SOLVED
\**************************************************************************************************/
// GC6ZZBB Engima-nano
char textGC6ZZBB[]=
"CRSMDDACIGRLKUPAHWCYFGDSEPBHSYPYYDDNWUDMBRKT"
"GPDULRSDTRWWYWVLWKVRIBHHWFVCDXVIEREHLGSQSBIQU"
"DGACRUFWBMYRSPYGBKESJLNNFTVAGSOXBDIOXJACSJRSAV"
"VXDAWBIMEDLQSLQKLFHATDCUGFPOYSBKPBSFLRHUPXDMM"
"TTDPRKZCOCNZDSULIHEJGLCLVQWXVAZZPWMOOKPPFWDSQ"
"VW";

// After removing the ROT13 encoding, this is resulted
// This is enigma encoded text
// UKW B, I II III, R 1 1 1, G 23 23 23, AB CD EF GH IJ KL MN OP QR ST UV WX YZ
char replyGC6ZZBB[]=
"QLTPKMZRJFEKXOWPAZXPJJJQLCIVDSVFUMCNUGRVTLXEEVYT"
"WDEFZQAMITJUSFQCRNMYHXVIFGRPHKBJBEAPDPJWBYTIILQM"
"AZIMWFNGLJJISZXFQURMHWWVIKUJVJHRWYJDKHVPYXCBFUOL"
"FCMJWTXFMNJBRFONYOQTSWQGKETQFGTNKUIWHSTCOAFJKOHX"
"HYRIHNLZEWJQQBABYIKUWXGCINOCVQPEBQJYXKUMWEDGBJPA"
"LDRUSFELKUIHPRHDAEXHGKMAUMHIIKKIAHPSJUABXMJKDJHD"
"JVQEUHOIIYYJMIVKDUEBLVGRKJMHECFYAYIKDNJWYDWJSTBZ"
"PIJQMQAPNKWOOZEJUKYVZECNKAYGADJHMBZAFGWSGXZYHIUY"
"MRJUVZOZVMCHZGILJZGJOBEJHIXJQXQEGMTDFVHXMAVDHDRO"
"HBKKZNAHICTDMLUXHEULAYCPOSQTGDAPJMIXOMGGRIWRTPCQ"
"JUJTCJEWBKPYQHVEWURAKVMJIRNPRCEEPARIUMCWTHILQLDZ"
"MRSDSRMAOQTLSUFVUYPDKGHTIGTLRMMBZPVUKMCHUKZKUPRK"
"EVYJIBWVZCXVXNHMTZEFZXVVPQBGTTJJHMQTUSCYFAGXXQOJ"
"JFNKQTXAXRLZGDJEOMXNAJWHVXMSHIVUUAWGPDSZKBHUKJVA"
"NRSLCDRUYEETMZAMBODUPCIWSEOHZYMSTEAFNKDEXPPKMWUN"
"RCAVOKVSWQWOKSFBXANMMUUIAYFLWNMUAWGGOGASBYERVJCL"
"PCBVNWAGMWEMUYJIMAQJJGDADNAWMPKKPFFFKXXPSLMUZSLB"
"EQJILYZZAXLYSTAAVIPOSFBWYBPOSFBHNQVXICOKHFZVNKZG"
"FJLUTYUGFGGAGKPZOAJDCRWIFZPKMCDTSVMLUMPNKSKDGNYZ"
"PUJQMEBCIPYAIPWTAGQBSEYLNHNUFDGGTVLJWUYSSAWCZMFA"
"OUVUWJQIGQFTACHWENNSHUNNRUKXWCOPWFLAPAUTROCMEJVC"
"UZMHPJXWPEONLUWCEHXWDGTBOUKZWRTYGYHVTBAFOVPEHTYY"
"KWMLBGVIJIVMUEZYZPGKRTMBXLIXBYWOPVQXZBWYBDJGVLHA"
"VEPDOQZAPRTFETCRZUFUTKOOZWTGPOIUKJKQPPIUKKQXHRZP"
"LVINXQOCJGXNVRFWDNADOVZWPBUQVKYLTHICCXVMEPMQTCGQ"
"NILDTBOXXDAAUZYANLKWMLZNTRFMZUEJQRZFKDSOCOFVYLUV"
"MIIWOOKAXLQEKRJGGDCDQLJMNGKDKBHMZJZOPYKGHPNIMIDR"
"UXEMRGVFYNZDCTXKGMHUEYMGZAUEIQOCDKHMIGURNEVBXLJL"
"PYLGDEBAKZJXTTRRIZUFZKBAQWQWBUXMGNLRVXEAWJTPAFWQ"
"HALGLSHFAFPQMSADGINEXECUDJDCBWEOEQJCWBNGLHIPXGJU"
"BWRYLYLYNABZRUEWCKSUBWCYJGLYZBFVFLAMEVRPTRAHWYKH"
"UFQFRMYXPJOHNVZAOVBFIGCIJONBKNVZXMVNBSXAWVEECXKW"
"WNOVVRRGSAJAZEDTQMKCFSGLDWSDFJCNZQEUFDGJLPMFMAGC"
"BZEJEMGGHRXEDBDENGDJZVXZTJNKTYJXUGHDHXNKZBOWXJUC"
"IZNHHITGFEHAMFDQXKSYWBQILNXXMNRJBHKZPBVGQDPKMSGJ"
"XICNRGSPKQWMTBLOVSXQOVIIBLHZCAUFKQSBAGHHNLAPRJJG"
"PEAIOULZSNJVBPHIERCWSGVRAXRVBIZGALTMXRZLTCICAPAD"
"YSLBUTXVEBACZDXJGGMRBAIXSIEDPSACVTFPTXOQLHSEZTRQ"
"ETYTLABBKDDXUCHEBWNFUMGUQJTDQNCPYLNWPFZFJZUNFGQJ"
"CYQLSXDQKKNRJGPHFPKHDUPEWBJJJSVCLBCSIJMJVUDKUXRF"
"IQIUZTNENNHZNWLOJDVPNYPYIRMOUUXEFYMPCROOSKKGAJOH"
"UPLXLHDAOHDQEHYFTYFKZNUHUNXAGDPNUNDEZEFJBXUKQCAP"
"MXFCNKQWKKCLYUESQJLSFMACBYRDJUSJIHDCMXDARSAPDQGM"
"VJVQVNYGTRVBKURGCEZQTLMFTOTFSJOYXLATZHJARLNMKYXX"
"AIJIWMWVRECNJDXCVEUZLMNXIEVARCVUEHAMPAHCRZUJNTIJ"
"DAMACDLJCRIGNKXFGALBUAKHLCZWTMGQDRTWUMKGSBZDGQGK"
"QZCUQQXEVDDXBLZPIRQMPUHTQNKCNAAKYQLKWSUELLXDQBMU"
"MOLFXKEOZZLBVXSFTPULYPUZGFJYTMUPXIVOUYACHYVASEBI"
"NORMVEPMJKXCFNULBJURDBDDKXVADTGOUDDXTXZPZNTJFPIU"
"AUGSQSIAHSNBZLBBWVSSCYICSYATXDUJZEMFDQIVUTKWCFJZ"
"KHEEQNJAWDAVTOELFOKWBLXGSSFBFQAXMUGIJEXWKZPJOSNB"
"ZJFXLZHPXAJFGLOHNBWPMPNCMBCINDWLWODISOZXTARGYCNM"
"HIUMTZHLGGOCOGWPNQTBVGCBCVJGVAWSIJNMKBZMXMBVYWQD"
"RMBJHPILKIMTWPQBNFQMKKURZEOYRZHESYXHDWILXMZHMKWA"
"ZEFBOWEYJSKJSFHRMQIGMHYHMWPAQTXQYVRCBNKCGHITSQYH"
"SADFAJTINESFMNJMWTIXCEXTGRKOGOOIZIJGAYNFDQDZXARQ"
"IORJNYXHLECSWTFRGZVKWLUGTDBQRREESCNOBBVOLDBRVNKN"
"QOZRVOVZDTKGOCSRYTYJFLWTGLEIXFTZZHNCYKKBVLRZCYEN"
"UKMXQSCFDDIKTODTCFIUTIVXQLVKWTKRGETZXFRQKTPHMXPE"
"LOSOQYQUTCBSMLKEBBTUEKMLLBCQEFWQMLKDBWFHMBTUNGHG"
"CDSYVURJZSPOHYRUFETJKZKLYVUKUVRUEZDWBYAOKPLRBNPH"
"KWTJJUBLWXRLVODBNCHNZKLGXZMPZEQZLNORDSOLPFFBSIRL"
"FQSEURQWXHDSKLPXVFCVVEYKHLVUZAYYLQAIXKJZFPIYHKOA"
"AVAEAXVHJWTLISBNUSIDNWYTIWXXCVYUNZPCTVHMUEGVCSIN"
"XYPAFTJFQEWEMBNXCRMVOOTCBUMUAPMTFITWAQRGHUAWIHVC"
"JRZEMOQQNEQUDLMCMUQWJENQZAFFR";

// This is the original cipher from the website
// as posted by MET218
// The first level of encoding is ROT13
char replyGC6ZZBB_2[]=
"DYGCXZMEWSRXKBJCNMKCWWWDYPVIQFISHZPAHTEIGYKRRILG"
"JQRSMDNZVGWHFSDPEAZLUKIVSTECUXOWORNCQCWJOLGVVYDZ"
"NMVZJSATYWWVFMKSDHEZUJJIVXHWIWUEJLWQXUICLKPOSHBY"
"SPZWJGKSZAWOESBALBDGFJDTXRGDSTGAXHVJUFGPBNSWXBUK"
"ULEVUAYMRJWDDONOLVXHJKTPVABPIDCRODWLKXHZJRQTOWCN"
"YQEHFSRYXHVUCEUQNRKUTXZNHZUVVXXVNUCFWHNOKZWXQWUQ"
"WIDRHUBVVLLWZVIXQHROYITEXWZURPSLNLVXQAWJLQJWFGOM"
"CVWDZDNCAXJBBMRWHXLIMRPAXNLTNQWUZOMNSTJFTKMLUVHL"
"ZEWHIMBMIZPUMTVYWMTWBORWUVKWDKDRTZGQSIUKZNIQUQEB"
"UOXXMANUVPGQZYHKURHYNLPCBFDGTQNCWZVKBZTTEVJEGCPD"
"WHWGPWRJOXCLDUIRJHENXIZWVEACEPRRCNEVHZPJGUVYDYQM"
"ZEFQFEZNBDGYFHSIHLCQXTUGVTGYEZZOMCIHXZPUHXMXHCEX"
"RILWVOJIMPKIKAUZGMRSMKIICDOTGGWWUZDGHFPLSNTKKDBW"
"WSAXDGKNKEYMTQWRBZKANWJUIKZFUVIHHNJTCQFMXOUHXWIN"
"AEFYPQEHLRRGZMNZOBQHCPVJFRBUMLZFGRNSAXQRKCCXZJHA"
"EPNIBXIFJDJBXFSOKNAZZHHVNLSYJAZHNJTTBTNFOLREIWPY"
"CPOIAJNTZJRZHLWVZNDWWTQNQANJZCXXCSSSXKKCFYZHMFYO"
"RDWVYLMMNKYLFGNNIVCBFSOJLOCBFSOUADIKVPBXUSMIAXMT"
"SWYHGLHTSTTNTXCMBNWQPEJVSMCXZPQGFIZYHZCAXFXQTALM"
"CHWDZROPVCLNVCJGNTDOFRLYAUAHSQTTGIYWJHLFFNJPMZSN"
"BHIHJWDVTDSGNPUJRAAFUHAAEHXKJPBCJSYNCNHGEBPZRWIP"
"HMZUCWKJCRBAYHJPRUKJQTGOBHXMJEGLTLUIGONSBICRUGLL"
"XJZYOTIVWVIZHRMLMCTXEGZOKYVKOLJBCIDKMOJLOQWTIYUN"
"IRCQBDMNCEGSRGPEMHSHGXBBMJGTCBVHXWXDCCVHXXDKUEMC"
"YIVAKDBPWTKAIESJQANQBIMJCOHDIXLYGUVPPKIZRCZDGPTD"
"AVYQGOBKKQNNHMLNAYXJZYMAGESZMHRWDEMSXQFBPBSILYHI"
"ZVVJBBXNKYDRXEWTTQPQDYWZATXQXOUZMWMBCLXTUCAVZVQE"
"HKRZETISLAMQPGKXTZUHRLZTMNHRVDBPQXUZVTHEARIOKYWY"
"CLYTQRONXMWKGGEEVMHSMXONDJDJOHKZTAYEIKRNJWGCNSJD"
"UNYTYFUSNSCDZFNQTVARKRPHQWQPOJRBRDWPJOATYUVCKTWH"
"OJELYLYLANOMEHRJPXFHOJPLWTYLMOSISYNZRIECGENUJLXU"
"HSDSEZLKCWBUAIMNBIOSVTPVWBAOXAIMKZIAOFKNJIRRPKXJ"
"JABIIEETFNWNMRQGDZXPSFTYQJFQSWPAMDRHSQTWYCZSZNTP"
"OMRWRZTTUEKRQOQRATQWMIKMGWAXGLWKHTUQUKAXMOBJKWHP"
"VMAUUVGTSRUNZSQDKXFLJODVYAKKZAEWOUXMCOITDQCXZFTW"
"KVPAETFCXDJZGOYBIFKDBIVVOYUMPNHSXDFONTUUAYNCEWWT"
"CRNVBHYMFAWIOCUVREPJFTIENKEIOVMTNYGZKEMYGPVPNCNQ"
"LFYOHGKIRONPMQKWTTZEONVKFVRQCFNPIGSCGKBDYUFRMGED"
"RGLGYNOOXQQKHPUROJASHZTHDWGQDAPCLYAJCSMSWMHASTDW"
"PLDYFKQDXXAEWTCUSCXUQHCRJOWWWFIPYOPFVWZWIHQXHKES"
"VDVHMGARAAUMAJYBWQICALCLVEZBHHKRSLZCPEBBFXXTNWBU"
"HCYKYUQNBUQDRULSGLSXMAHUHAKNTQCAHAQRMRSWOKHXDPNC"
"ZKSPAXDJXXPYLHRFDWYFSZNPOLEQWHFWVUQPZKQNEFNCQDTZ"
"IWIDIALTGEIOXHETPRMDGYZSGBGSFWBLKYNGMUWNEYAZXLKK"
"NVWVJZJIERPAWQKPIRHMYZAKVRINEPIHRUNZCNUPEMHWAGVW"
"QNZNPQYWPEVTAXKSTNYOHNXUYPMJGZTDQEGJHZXTFOMQTDTX"
"DMPHDDKRIQQKOYMCVEDZCHUGDAXPANNXLDYXJFHRYYKQDOZH"
"ZBYSKXRBMMYOIKFSGCHYLCHMTSWLGZHCKVIBHLNPULINFROV"
"ABEZIRCZWXKPSAHYOWHEQOQQXKINQGTBHQQKGKMCMAGWSCVH"
"NHTFDFVNUFAOMYOOJIFFPLVPFLNGKQHWMRZSQDVIHGXJPSWM"
"XURRDAWNJQNIGBRYSBXJOYKTFFSOSDNKZHTVWRKJXMCWBFAO"
"MWSKYMUCKNWSTYBUAOJCZCAPZOPVAQJYJBQVFBMKGNETLPAZ"
"UVHZGMUYTTBPBTJCADGOITPOPIWTINJFVWAZXOMZKZOILJDQ"
"EZOWUCVYXVZGJCDOASDZXXHEMRBLEMURFLKUQJVYKZMUZXJN"
"MRSOBJRLWFXWFSUEZDVTZULUZJCNDGKDLIEPOAXPTUVGFDLU"
"FNQSNWGVARFSZAWZJGVKPRKGTEXBTBBVMVWTNLASQDQMKNED"
"VBEWALKUYRPFJGSETMIXJYHTGQODEERRFPABOOIBYQOEIAXA"
"DBMEIBIMQGXTBPFELGLWSYJGTYRVKSGMMUAPLXXOIYEMPLRA"
"HXZKDFPSQQVXGBQGPSVHGVIKDYIXJGXETRGMKSEDXGCUZKCR"
"YBFBDLDHGPOFZYXROOGHRXZYYOPDRSJDZYXQOJSUZOGHATUT"
"PQFLIHEWMFCBULEHSRGWXMXYLIHXHIEHRMQJOLNBXCYEOACU"
"XJGWWHOYJKEYIBQOAPUAMXYTKMZCMRDMYABEQFBYCSSOFVEY"
"SDFRHEDJKUQFXYCKISPIIRLXUYIHMNLLYDNVKXWMSCVLUXBN"
"NINRNKIUWJGYVFOAHFVQAJLGVJKKPILHAMCPGIUZHRTIPFVA"
"KLCNSGWSDRJRZOAKPEZIBBGPOHZHNCZGSVGJNDETUHNJVUIP"
"WEMRZBDDARDHQYZPZHDJWRADMNSSE";

void gcEnigmaNano()
{
    int numOfThreads=6;

    // Create a list of permutations with only UKW B
    LinkedList* walzenPermutations  =getWalzenPermutations(ENIGMATYPE_M3, M3_ARMY_1938);
    LinkedList* walzePermutations   =linkedListCreate();
    int*        permutation         =malloc(sizeof(int));
    permutation[0]                  =1; // Index of UKW B
    linkedListAppendObject(walzePermutations, permutation);
    LinkedList* permutations=combinePermutations(walzePermutations, 1, walzenPermutations, 3);
    destroyPermutations(walzePermutations);
    destroyPermutations(walzenPermutations);

//    setEvaluationMethod(METHOD_IOC, 13, 13, 0, NULL);
//    setEvaluationMethod(METHOD_IOC_DEEP, 13, 13, 3, NULL);
//    setEvaluationMethod(METHOD_IOC_NGRAM, 13, 6, 3, "DE");
//    setEvaluationMethod(METHOD_IOC_NGRAM, 13, 6, 3, "GB");
//    setEvaluationMethod(METHOD_IOC_NGRAM, 13, 0, 3, "DE");
// TO DO
    IocRecipe* recipe=createDefaultIocRecipe(textGC6ZZBB, numOfThreads);
    recipe->method           =DEPTH_R3;
    recipe->evalWalzen       =EVAL_IOC;
    recipe->evalSteckers     =EVAL_IOC;
    recipe->maxSteckers      =13;
    recipe->maxSteckersInline=10;
    recipe->knownSteckers[0] ='\0';
    recipe->ngramSize        =3;
    strncpy(recipe->ngramSet, "DE", MAX_NGRAMSETSIZE);
    recipe->scoreListSize    =400;
    recipe->numberOfSolutions=100;
    iocDecodeText(*recipe, permutations);
    destroyIocRecipe(recipe);
    destroyPermutations(permutations);
}

/**************************************************************************************************\
* Enigma cipher from GC6ZZBB geochache. It is a short cipher.
* FROM THE GEOCACHE WE KNOW FOLLOWING:
* - http://enigmaco.de/enigma/enigma_de.html was used to encrypt; therefore
* - Three Walzen out of I-V
* - R1 = R2 = R3 = 1
* - UKW B
* - up to 13 steckers
* - Language is probably german
*
* DO NOT RUN THIS EXAMPLE, IT TAKES INCREDIBLY LONG TIME (ALMOST 9 DAYS) SINCE IT ALMOST
* BRUTE FORCING. 
*
* It almost finds the correct solution:
* 1: UKW B   I  II III R  1  1 14 G 23 23 10 - AB CD EF GH IJ KL MN OP QR ST UV WX YZ - 0.045331
* WHEN THIS CACHL NACQHNOULQHP IMMEDIATELY CAGWJMPWZRCRPPLONA FEW MONTHS ABWBTAQDTCEPGBN A 
* FAMOUS ENIGMM LMGONJYVSYAWDNT MANAGE TO SOUMLSMRGOAORJSOT HAPPY WITH THPQVDWZNNNLBETRNEDOU..
*
* The precise solution is easily found using Cryptii:
* UKW B, I II III, R 1 1 1, G 23 23 23, AB CD EF GH IJ KL MN OP QR ST UV WX YZ
* 
* WHEN THIS CACHE CAME ONLINE IT IMMEDIATELY CAUGHT MY ATTENTION A FEW
* MONTHS AGO I HAD WORKED ON A FAMOUS ENIGMA PROBLEM BUT DIDNT MANAGE TO
* SOLVE IT AND I WAS NOT HAPPY WITH THAT THIS CACHE TURNED OUT TO BE THE
* MOTIVATION I NEEDED TO GET TURN BACK TO MY ENIGMA PROJECT AT FIRST I
* WORKED ONLY ON THE CACHE ENIGMA PROJECT AS IT SEEMED EASIER THAN THE
* MORE FAMOUS ENIGMA PROBLEM BUT AFTER A WEEK OR SO I STILL HADNT CRACKED
* IT SO I STARTED TO SEARCH THE INTERNET FOR MORE INFORMATION ABOUT HOW
* TO CRACK AN ENIGMA IF YOU DO NOT KNOW THE SETTINGS THERE WAS A LOT TO
* READ AND PROCESS WITH THIS NEW INFORMATION I IMPROVED MY CODE AND RAN
* IT AGAIN ON MY YEAR OLD MACHINE AFTER RUNNING FOR DAYS AND DAYS IT
* STILL DIDNT COME WITH A CRACK THEN I CHANGED IT SO THAT I MADE USE OF
* MULTI THREADING THIS WAY I COULD USE THE CORES OF MY CPU STILL NO RESULT
* WHEN I STILL DIDNT MANAGE TO CRACK IT I TURNED BACK TO THE INTERNET AND
* READ EVEN MORE WHITE PAPERS ABOUT DETECTING INFORMATION IN NOISE ETC
* EVERYTHING I LEARNED I PUT INTO PRACTISE BUT IT STILL DIDNT BRING ME
* THE SOLUTION AT ONE TIME AT A CHILDS PARTY WHERE WE HAD TO BABYSIT MY
* WIFE AND ME WROTE DOWN ON A NAPKIN A WAY TO CRACK THE ENIGMA WHICH DIDNT
* REQUIRE A LOT OF ENCRYPTING OR DECRYPTING IT WORKED REALLY FAST ON ALL
* THE TEST MESSAGES I TESTED IT ON BUT I STILL DIDNT MANAGE TO CRACK THIS
* CACHE ON TWO OCCASSIONS I UPDATED THE CO WITH MY PROGRESS OR LACK OF IT
* THEN IT DAWNED ON ME WHAT MIGHT BE THE REASON I HADNT BROKEN IT YET SO I
* DECIDED TO FOCUS MY ATTENTION ON THE OTHER MORE FAMOUS ENIGMA PROBLEM
* FIRST SO LONG AS I DIDNT HAVE A SOLUTION FOR THIS PROBLEM WHILE WORKING
* ON THAT PROBLEM I DECIDED TO CONTACT A PERSON WHO HAD WRITTEN SOME OF
* THE WHITE PAPERS I HAD READ TO SEE IF HE WAS INTERESTED IN THIS
* PROBLEM I WAS NOT INTERESTED IN THE SOLUTION BECAUSE I WANTED TO BREAK
* IT MYSELF BUT I WANTED CONFIRMATION THAT IT COULD BE BROKEN AT ALL IF
* HE COULD BREAK IT IT WOULD BE A BOOST TO MY MORALE TO CONTINUE ON THIS
* HOPELESSLY LOOKING PROJECT TO MY SURPRISE THE AUTHOR REACTED VERY
* ENTHOUSIASTIC ABOUT MY REQUEST HE AND A COLLEAGUE OF HIS WERE VERY
* INTERESTED IN THE PROBLEM AND STARTED TO WORK ON IT RIGHT AWAY MEAN
* WHILE I CONTINUED WORKING ON THE FAMOUS ENIGMA PROBLEM AND FINALLY
* MANAGED TO SOLVE IT THIS WAS A GREAT MOMENT SO I IMMEDIATELY SHIFTED MY
* FOCUS AGAIN ON THIS PUZZLE A FEW DAYS LATER WHEN I WAS AT WORK I GOT A
* MESSAGE FROM THE AUTHOR THAT HE HAD INDEED CRACKED THIS PROBLEM HE WAS
* GLAD TO CONCLUDE THAT THEIR SOFTWARE WAS ALSO ABLE TO CRACK THIS
* PROBLEM WHEN I GOT HOME I MANUALLY CHECKED ALL THE BEST CANDIDATES I
* HAD FOUND SO FAR THEN I FOCUSED ON A FEW PROMISING ONES AND SUDDENLY I
* NOTICED SOMETHING I QUICKLY REWROTE SOME OF MY CODE AND STARTED
* ATTACKING ONE PARTICULAR CANDIDATE A FEW MINUTES LATER I WAS STARING
* AT THE PLAIN TEXT IT WAS NOW TOTALLY CLEAR WHERE THE CACHE WAS HIDDEN
* AND WHAT I HAD TO DO TO GET IT THE MOMENT MY WIFE CAME HOME BACK FROM
* WORK WE ALSO THE KIDS JUMPED IN THE CAR TO DRIVE ALL THE WAY TO GERMANY
* TO FINALLY FIND AND LOG THE CACHE ALL IN ALL IT HAD COST ME FIVE WEEKS
* OF TIRELESSLY READING THINKING CODING AND TRYING THE FIELD WORK TURNED
* OUT TO BE A BIG DISAPPOINTMENT FIRST WE COULDNT REALLY SEARCH AS THERE
* WERE MUGGLES IN THE AREA LATER THAT EVENING WE DID A SEARCH IN THE DARK
* BUT FAILED TO FIND THE CACHE DISAPPOINTED WE DROVE BACK ALL THE WAY TO
* OUR HOME IN THE NETHERLANDS WE CAME BACK AFTER MIDNIGHT AND DECIDED NOT
* TO GO BACK UNLESS WE HAD A BETTER IDEA OR WE WOULD HAVE MORE DAYLIGHT
* TODAY I WENT BACK TO GERMANY WITH TWO GEOCACHE FRIENDS THEY WERE
* WILLING TO HELP ME SEARCH BUT WOULD NOT TAKE ANY PODIUM SPOTS AND LEAVE
* THE TTF FOR SOMEONE WHO ALSO CRACKED THE ENIGMA CODE WHEN WE GOT THERE
* IT WAS RAINY BUT STILL LIGHT WE WERE THERE ONLY A FEW SECONDS WHEN ONE
* OF THEM ALREADY FOUND IT AT A SPOT I HAD SEARCHED THREE TIMES IN THE
* DARK FINALLY A SUCCESFUL RESULT AFTER ALL THOSE WEEKS ATTACKING THIS
* PUZZLE
*
\**************************************************************************************************/
void gcEnigmaNanoReply()
{
    int numOfThreads=6;

    // Create a list of permutations with only UKW B
    LinkedList* walzenPermutations  =getWalzenPermutations(ENIGMATYPE_M3, M3_ARMY_1938);
    LinkedList* walzePermutations   =linkedListCreate();
    int*        permutation         =malloc(sizeof(int));
    permutation[0]=1; // Index of UKW B
    linkedListAppendObject(walzePermutations, permutation);
    LinkedList* permutations=combinePermutations(walzePermutations, 1, walzenPermutations, 3);
    destroyPermutations(walzePermutations);
    destroyPermutations(walzenPermutations);

    IocRecipe recipe;
    recipe.enigmaType       =ENIGMATYPE_M3;
    recipe.walzeSet         =M3_ARMY_1938;
    recipe.method           =DEPTH_R3;
    recipe.evalWalzen       =EVAL_IOC;
    recipe.evalSteckers     =EVAL_IOC;
    recipe.maxSteckers      =13;
    recipe.maxSteckersInline=10;
    recipe.knownSteckers[0] ='\0';
    recipe.ngramSize        =0;
    strncpy(recipe.ngramSet, "DE", MAX_NGRAMSETSIZE);
    recipe.scoreListSize    =400;
    recipe.numberOfSolutions=10;
    recipe.numberOfThreads  =numOfThreads;
    recipe.cipher           =replyGC6ZZBB;
    recipe.cipherSize       =MAX_TEXT;
    iocDecodeText(recipe, permutations);
    destroyPermutations(permutations);
}


/**************************************************************************************************\
* 
* Geocache Code Breakers, GC6R1M1, level 5
* Hint: met twee een acht x ab x cd x ef
* SOLVED
*
\**************************************************************************************************/
// Code breakers GC6R1M1
char textCodeBreakers[]= "MCIKVFMLPDWBWMLQRVKEYPSFBVYHLSGSYAFZPXZCBFWPEUMWMBUM"
                         "GCUMKCZPQJEEXEEEWOSBXQJTHQEDNJMSJENPWYSCKWOVPMAYWNQ";

void gcCodeBreakers()
{
    printf("#####################################################################################\n");
    printf("# GEOCACHE GC6R1M1, Code Breakers - Level 5\n");
    printf("#####################################################################################\n");


    // FROM THE GEOCACHE WE KNOW FOLLOWING:
    // III I II, UKW B, 
    // We create a custom permutations list with just one permutation
    LinkedList* permutations=linkedListCreate();
    int*        permutation =malloc(4*sizeof(int));
    permutation[0]=1; // Index of UKW B
    permutation[1]=2; // III
    permutation[2]=0; // I
    permutation[3]=1; // II
    linkedListAppendObject(permutations, permutation);

    // program the IoC solver
    IocRecipe recipe;
    recipe.enigmaType       =ENIGMATYPE_M3;
    recipe.walzeSet         =M3_ARMY_1938;
    recipe.method           =DEPTH_NONE;
    recipe.evalWalzen       =EVAL_IOC;
    recipe.evalSteckers     =EVAL_IOC;
    recipe.maxSteckers      =3;
    recipe.maxSteckersInline=0;
    strncpy(recipe.knownSteckers, "AB CD EF", MAX_STECKER_STRING-1);
    recipe.ngramSize        =3;
    strncpy(recipe.ngramSet, "NL", MAX_NGRAMSETSIZE);
    recipe.scoreListSize    =25;
    recipe.numberOfSolutions=5;
    recipe.numberOfThreads  =1;
    recipe.cipher           =textCodeBreakers;
    recipe.cipherSize       =MAX_TEXT;
    recipe.displayFormat    =MESSAGEFORMAT_TEXT;
//    recipe.cipher           =text11_test;
    iocDecodeText(recipe, permutations);
    destroyPermutations(permutations);
}

/**************************************************************************************************\
* 
* Geocache: Enigma, GC7ENW4
* Rad-Auftrag: IV, II, V
* Ring-Einstellungen: 15, 23, 26
* Stecker Anschlüsse: EJ OY IV AQ KW FX MT PS lU BD
* NOT SOLVED
*
\**************************************************************************************************/
// Enigma GC7ENW4
char textGC7ENW4[]= "EKSY YUIC OERV TZZF FVON TTXN ZNOC QTJF CSCZ DJOM ADRV BEZK OHSG RIFH KJEP "
                    "MQMT MKBG FNRN ZXPG OYTX AASW DYOL QJJR JCLN";

void gcEnigma()
{
    printf("#####################################################################################\n");
    printf("# GEOCACHE GC7ENW4, 'Enigma'\n");
    printf("#####################################################################################\n");

    LinkedList* permutations=linkedListCreate();
    int*        permutation =malloc(4*sizeof(int));
    permutation[0]=1; // Index of UKW B
    permutation[1]=1; // II
    permutation[2]=3; // IV
    permutation[3]=4; // V
    linkedListAppendObject(permutations, permutation);
    permutation     =malloc(4*sizeof(int));
    permutation[0]=2; // Index of UKW C
    permutation[1]=1; // II
    permutation[2]=3; // IV
    permutation[3]=4; // V
    linkedListAppendObject(permutations, permutation);

    // program the IoC solver
    IocRecipe recipe;
    recipe.enigmaType       =ENIGMATYPE_M3;
    recipe.walzeSet         =M3_ARMY_1938;
    recipe.method           =DEPTH_NONE;
    recipe.evalWalzen       =EVAL_IOC;
    recipe.evalSteckers     =EVAL_IOC;
    recipe.maxSteckers      =3;
    recipe.maxSteckersInline=0;
    strncpy(recipe.knownSteckers, "EJ OY IV AQ KW FX MT PS LU BD", MAX_STECKER_STRING-1);
    recipe.ngramSize        =0;
    recipe.ngramSet[0]      =0;
    recipe.scoreListSize    =25;
    recipe.numberOfSolutions=25;
    recipe.numberOfThreads  =1;
    recipe.cipher           =textGC7ENW4;
    recipe.cipherSize       =MAX_TEXT;
    recipe.displayFormat    =MESSAGEFORMAT_TEXT;
    iocDecodeText(recipe, permutations);
    destroyPermutations(permutations);
}



